### ISSUE TITLE
LLVM Debian/Ubuntu nightly packages keys

### ISSUE THREAD

**Issue by ChipmunkV** [sylvestre/llvm-jenkins.debian.net#2]
The page http://apt.llvm.org/ advises to do the following to install the keys for the http://apt.llvm.org repositories:

    wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -

Could you please provide the keys or their fingerprints here on GitHub (or just confirm here that 6084F3CF814B57C1CF12EFD515CF4D18AF4F7421 is the right fingerprint)? Or enable HTTPS on the http://apt.llvm.org/?

**Comment by sylvestre** [comment]
http://apt.llvm.org/ has now the fingerprint (this was the right one). 
For the https, I don't control the admin, maybe @asl have an update on this?

**Comment by ChipmunkV** [comment]
> http://apt.llvm.org/ has now the fingerprint

Doesn't help much since the page itself is served via http. But thanks for the key confirmation.
